# Generated by Django 2.1.1 on 2018-10-18 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('title', models.CharField(max_length=120)),
                ('rank', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('loc', 'Nacionales'), ('int', 'Internacionales'), ('opn', 'Opinión'), ('ent', 'Entretenimiento'), ('dep', 'Deportes')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='links.Link')),
            ],
        ),
    ]
