# Generated by Django 2.1.2 on 2018-11-01 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20181028_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
